name: Perf

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: perf-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  run:
    name: Run Perf
    runs-on: ubuntu-20.04
    steps:
    - name: Trigger NetPerf Workflow
      uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570
      with:
        token: ${{ secrets.NET_PERF_TRIGGER }}
        repository: microsoft/netperf
        event-type: run-quic
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "name": "msquic"}'
    - name: Wait for NetPerf Workflow
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: scripts/wait-for-workflow.ps1 msquic ${{ github.sha }}
