name: Perf

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: perf-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  run:
    name: Run Perf
    runs-on: ubuntu-20.04
    steps:
    - name: Trigger NetPerf Workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.NET_PERF_TRIGGER }}
        repository: microsoft/netperf
        event-type: run-quic
        client-payload: '{"ref": "${{ github.ref }}"}'
